# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Form4.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Social_Efficiency_Window(object):
    def setupUi(self, Social_Efficiency_Window):
        Social_Efficiency_Window.setObjectName("Social_Efficiency_Window")
        Social_Efficiency_Window.resize(846, 600)
        self.centralwidget = QtWidgets.QWidget(Social_Efficiency_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.label_Technical_efficiency = QtWidgets.QLabel(self.centralwidget)
        self.label_Technical_efficiency.setGeometry(QtCore.QRect(110, 10, 601, 91))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_Technical_efficiency.setFont(font)
        self.label_Technical_efficiency.setObjectName("label_Technical_efficiency")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 100, 351, 211))
        self.groupBox.setObjectName("groupBox")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setGeometry(QtCore.QRect(80, 70, 261, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(80, 50, 271, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 70, 61, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_4.setGeometry(QtCore.QRect(80, 130, 261, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(80, 100, 341, 31))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 130, 61, 16))
        self.label_6.setObjectName("label_6")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(400, 100, 351, 211))
        self.groupBox_2.setObjectName("groupBox_2")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(80, 70, 261, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(80, 50, 271, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(10, 70, 61, 16))
        self.label_8.setObjectName("label_8")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_6.setGeometry(QtCore.QRect(80, 130, 261, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(80, 100, 341, 31))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(10, 130, 61, 16))
        self.label_10.setObjectName("label_10")
        Social_Efficiency_Window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Social_Efficiency_Window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 846, 21))
        self.menubar.setObjectName("menubar")
        Social_Efficiency_Window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Social_Efficiency_Window)
        self.statusbar.setObjectName("statusbar")
        Social_Efficiency_Window.setStatusBar(self.statusbar)

        self.retranslateUi(Social_Efficiency_Window)
        QtCore.QMetaObject.connectSlotsByName(Social_Efficiency_Window)

    def retranslateUi(self, Social_Efficiency_Window):
        _translate = QtCore.QCoreApplication.translate
        Social_Efficiency_Window.setWindowTitle(_translate("Social_Efficiency_Window", "Социальная эффективность"))
        self.label_Technical_efficiency.setText(_translate("Social_Efficiency_Window", "Социальная эффективность "))
        self.groupBox.setTitle(_translate("Social_Efficiency_Window", "Сн"))
        self.label_3.setText(_translate("Social_Efficiency_Window", "Доля «социальных» абонентов"))
        self.label_4.setText(_translate("Social_Efficiency_Window", "dсоц. аб ="))
        self.label_5.setText(_translate("Social_Efficiency_Window", "доля социально незащищенных граждан на\n"
"обслуживаемой территории"))
        self.label_6.setText(_translate("Social_Efficiency_Window", "dсоц. нез  ="))
        self.groupBox_2.setTitle(_translate("Social_Efficiency_Window", "Сп"))
        self.label_7.setText(_translate("Social_Efficiency_Window", "Доля «социальных» абонентов"))
        self.label_8.setText(_translate("Social_Efficiency_Window", "Nудовл ="))
        self.label_9.setText(_translate("Social_Efficiency_Window", "доля социально незащищенных граждан на\n"
"обслуживаемой территории"))
        self.label_10.setText(_translate("Social_Efficiency_Window", "Nопрош  ="))


