# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Form2.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EconomicEfficiencyWindow(object):
    def setupUi(self, EconomicEfficiencyWindow):
        EconomicEfficiencyWindow.setObjectName("EconomicEfficiencyWindow")
        EconomicEfficiencyWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(EconomicEfficiencyWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_Technical_efficiency = QtWidgets.QLabel(self.centralwidget)
        self.label_Technical_efficiency.setGeometry(QtCore.QRect(140, 10, 601, 91))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_Technical_efficiency.setFont(font)
        self.label_Technical_efficiency.setObjectName("label_Technical_efficiency")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(250, 330, 261, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(250, 200, 261, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(210, 250, 41, 16))
        self.label_5.setObjectName("label_5")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(250, 290, 271, 31))
        self.label_8.setObjectName("label_8")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(210, 200, 41, 16))
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(210, 330, 41, 16))
        self.label_7.setObjectName("label_7")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(250, 250, 261, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(250, 180, 271, 16))
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(250, 230, 271, 16))
        self.label_6.setObjectName("label_6")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.buttonBox.setGeometry(QtCore.QRect(310, 500, 156, 23))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        EconomicEfficiencyWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(EconomicEfficiencyWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        EconomicEfficiencyWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(EconomicEfficiencyWindow)
        self.statusbar.setObjectName("statusbar")
        EconomicEfficiencyWindow.setStatusBar(self.statusbar)

        self.retranslateUi(EconomicEfficiencyWindow)
        QtCore.QMetaObject.connectSlotsByName(EconomicEfficiencyWindow)

    def retranslateUi(self, EconomicEfficiencyWindow):
        _translate = QtCore.QCoreApplication.translate
        EconomicEfficiencyWindow.setWindowTitle(_translate("EconomicEfficiencyWindow", "Экономическая эффективность"))
        self.label_Technical_efficiency.setText(_translate("EconomicEfficiencyWindow", "Экономическая эффективность "))
        self.label_5.setText(_translate("EconomicEfficiencyWindow", "Fi ="))
        self.label_8.setText(_translate("EconomicEfficiencyWindow", "площадь географической территории, на которой\n"
"осуществляется вещание"))
        self.label_4.setText(_translate("EconomicEfficiencyWindow", "Дгосi ="))
        self.label_7.setText(_translate("EconomicEfficiencyWindow", "S ="))
        self.comboBox.setItemText(0, _translate("EconomicEfficiencyWindow", "450"))
        self.comboBox.setItemText(1, _translate("EconomicEfficiencyWindow", "1800"))
        self.comboBox.setItemText(2, _translate("EconomicEfficiencyWindow", "2000"))
        self.label_3.setText(_translate("EconomicEfficiencyWindow", "годовые доходы государства от i-го пользователя"))
        self.label_6.setText(_translate("EconomicEfficiencyWindow", "объем выделенного РЧС"))


