# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Form2.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets

from db import DBApi


class Ui_EconomicEfficiencyWindow(object):

    def result(self):
        db = DBApi()

        Dgosi = self.lineEdit_3.text()
        Fi = self.comboBox.currentText()
        S = self.lineEdit_5.text()

        if Dgosi != '' and S != '':
            a = int(int(Fi) * int(S))
            result_value = int(Dgosi) / int(a)
            self.label_All_result.setText(f'C2 = {str(result_value)}')
            db.add_basic_formula('C2', str(result_value))

        print('asd')



    def setupUi(self, EconomicEfficiencyWindow):
        EconomicEfficiencyWindow.setObjectName("EconomicEfficiencyWindow")
        EconomicEfficiencyWindow.resize(610, 452)
        self.centralwidget = QtWidgets.QWidget(EconomicEfficiencyWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_Technical_efficiency = QtWidgets.QLabel(self.centralwidget)
        self.label_Technical_efficiency.setGeometry(QtCore.QRect(10, 0, 601, 91))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_Technical_efficiency.setFont(font)
        self.label_Technical_efficiency.setObjectName("label_Technical_efficiency")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(170, 280, 261, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(170, 150, 261, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(130, 200, 41, 16))
        self.label_5.setObjectName("label_5")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(170, 240, 271, 31))
        self.label_8.setObjectName("label_8")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(130, 150, 41, 16))
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(130, 280, 41, 16))
        self.label_7.setObjectName("label_7")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(170, 200, 261, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(170, 130, 271, 16))
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(170, 180, 271, 16))
        self.label_6.setObjectName("label_6")
        self.Button_Result_Econom = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Result_Econom.setGeometry(QtCore.QRect(250, 370, 101, 41))
        self.Button_Result_Econom.setObjectName("Button_Result_Econom")
        self.label_All_result = QtWidgets.QLabel(self.centralwidget)
        self.label_All_result.setGeometry(QtCore.QRect(130, 330, 301, 16))
        self.label_All_result.setObjectName("label_All_result")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(200, 80, 201, 31))
        self.label_9.setObjectName("label_9")
        EconomicEfficiencyWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(EconomicEfficiencyWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 610, 21))
        self.menubar.setObjectName("menubar")
        EconomicEfficiencyWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(EconomicEfficiencyWindow)
        self.statusbar.setObjectName("statusbar")
        EconomicEfficiencyWindow.setStatusBar(self.statusbar)

        self.retranslateUi(EconomicEfficiencyWindow)
        QtCore.QMetaObject.connectSlotsByName(EconomicEfficiencyWindow)

        self.result()
        self.Button_res()

    def retranslateUi(self, EconomicEfficiencyWindow):
        _translate = QtCore.QCoreApplication.translate
        EconomicEfficiencyWindow.setWindowTitle(_translate("EconomicEfficiencyWindow", "Экономическая эффективность"))
        self.label_Technical_efficiency.setText(_translate("EconomicEfficiencyWindow", "Экономическая эффективность "))
        self.label_5.setText(_translate("EconomicEfficiencyWindow", "Fi ="))
        self.label_8.setText(_translate("EconomicEfficiencyWindow", "площадь географической территории, на которой\n"
                                                                    "осуществляется вещание"))
        self.label_4.setText(_translate("EconomicEfficiencyWindow", "Дгосi ="))
        self.label_7.setText(_translate("EconomicEfficiencyWindow", "S ="))
        self.comboBox.setItemText(0, _translate("EconomicEfficiencyWindow", "450"))
        self.comboBox.setItemText(1, _translate("EconomicEfficiencyWindow", "1800"))
        self.comboBox.setItemText(2, _translate("EconomicEfficiencyWindow", "2000"))
        self.label_3.setText(_translate("EconomicEfficiencyWindow", "годовые доходы государства от i-го пользователя"))
        self.label_6.setText(_translate("EconomicEfficiencyWindow", "объем выделенного РЧС"))
        self.Button_Result_Econom.setText(_translate("EconomicEfficiencyWindow", "Высчитать"))
        self.label_All_result.setText(_translate("EconomicEfficiencyWindow", "С2 ="))
        self.label_9.setText(_translate("EconomicEfficiencyWindow",
                                        "<html><head/><body><p><span style=\" font-size:20pt;\">C2 = </span><span style=\" font-family:\'Calibri\',\'sans-serif\'; font-size:20pt;\">Д</span><span style=\" font-family:\'Calibri\',\'sans-serif\'; font-size:20pt; vertical-align:sub;\">госi  </span><span style=\" font-family:\'Calibri\',\'sans-serif\'; font-size:20pt;\">/ F</span><span style=\" font-family:\'Calibri\',\'sans-serif\'; font-size:20pt; vertical-align:sub;\">i</span><span style=\" font-family:\'Calibri\',\'sans-serif\'; font-size:20pt;\"> *S</span></p></body></html>"))
        self.Button_Result_Econom.clicked.connect(self.result)

    def Button_res(self):
        self.Button_Result_Econom.clicked.connect(lambda: self.result)
        print('butt')

class Tech(QtWidgets.QWidget):  # (object):
    def __init__(self):
        super(Tech, self).__init__()
        self.setFixedSize(423, 293)

        self.lineEdit1 = QtWidgets.QLineEdit("", self)
        self.lineEdit1.resize(321, 51)
        self.lineEdit1.move(50, 80)

    def closeEvent(self, event):
        reply = QtWidgets.QMessageBox.question(
            self,
            "Exit",
            "Are you sure to quit?",
            QtWidgets.QMessageBox.Yes | QtWidgets.QMessageBox.No,
            QtWidgets.QMessageBox.No
        )

        if reply == QtWidgets.QMessageBox.Yes:
            event.accept()
        else:
            event.ignore()

if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    w = Tech()
    w.show()

    sys.exit(app.exec_())
